### ISSUE TITLE
Unable to flash software

### ISSUE THREAD

**Issue by JeroenVanHautte** [Oliv4945/eink#1]
Hi there!
We recently built the PCB as designed by spritesmod.
I ran your script without errors on a ubuntu VM, but I'm experiencing some trouble with the "make flash" command. My device is not able to find the ESP-12 module or flash to it. 

Is there a way to do this using a VM (in virtualbox)?
Do we need to connect the battery or is the usb connection enough?
Would you be willing to assist us in getting our setup working? Please contact me at jeroen.vanhautte@ugent.be.

Thanks in advance,
Jeroen

**Comment by Oliv4945** [comment]
Hi,

If you are using ESP-12 alone, you should change the [L31](https://github.com/Oliv4945/eink/blob/master/Makefile#L31) of the Makefile to `None`, and do the reset to bootloader sequence by yourself.

I did not study Sprite_tm schematics but USB connection should be enough.

**Comment by JeroenVanHautte** [comment]
Hi there!
I managed to use your tools to flash everything needed, but it's not working very well:
- In the case of booting after power loss:
1. Loading the image seems to work
2. Displaying it does nothing except wipe the connected eink screen

- In the case of a reset
1. A fatal exception occurs after about 10.5s.

- In both cases:
1. At first the AP is online
2. When trying to connect, the system crashes

Almost all of the crashes seem to have a cause 4. Any thoughts on this?

Kind regards,
Jeroen

**Comment by JeroenVanHautte** [comment]
We finally found the issue: flashing worked perfectly, but the peak current usage was higher than our supply could manage (220mA instead of 170 mA). This caused the fatal exceptions.
